name: Build & Upload Release Binaries

on:
  push:
    tags:
      - 'v*' # Trigger when you push a tag like v1.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            rid: win-x64
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64

    name: Build on ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish for ${{ matrix.rid }}
        run: |
          dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true -o publish-${{ matrix.rid }}

      - name: Zip output
        run: zip -r Blackjack-${{ matrix.rid }}.zip publish-${{ matrix.rid }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Blackjack-${{ matrix.rid }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
